# Generated by Django 4.1.3 on 2022-11-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='current_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
